import { Injectable, InternalServerErrorException, NotFoundException } from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { AiService } from '../ai/ai.service';

@Injectable()
export class ArtefactsService {
  constructor(
    private readonly supabaseService: SupabaseService,
    private readonly aiService: AiService,
  ) {}

  async findAll(projectId: string) {
    const { data, error } = await this.supabaseService.getClient()
      .from('artefacts')
      .select('*')
      .eq('project_id', projectId);

    if (error) throw new InternalServerErrorException(error.message);
    return data;
  }

  async findOne(projectId: string, id: string) {
    const { data, error } = await this.supabaseService.getClient()
      .from('artefacts')
      .select('*')
      .eq('project_id', projectId)
      .eq('id', id)
      .single();

    if (error || !data) throw new NotFoundException('Artefact not found');
    return data;
  }

  async generate(projectId: string, payload: any) {
    // 1. Call Gemini to generate content
    const generatedContent = await this.aiService.generateArtefact(payload.agentType, payload.prompt);
    
    // 2. Save to Supabase
    const { data, error } = await this.supabaseService.getClient()
      .from('artefacts')
      .insert({
        project_id: projectId,
        type: payload.type || 'code',
        name: `Generated by ${payload.agentType}`,
        content: generatedContent,
        format: 'markdown', // Defaulting to markdown for simplicity
        status: 'draft',
        generated_by: payload.agentType,
      })
      .select()
      .single();

    if (error) throw new InternalServerErrorException(error.message);
    return data;
  }

  async update(projectId: string, id: string, payload: any) {
    const { data, error } = await this.supabaseService.getClient()
      .from('artefacts')
      .update(payload)
      .eq('project_id', projectId)
      .eq('id', id)
      .select()
      .single();

    if (error) throw new InternalServerErrorException(error.message);
    return data;
  }
}
