import {
  Injectable,
  InternalServerErrorException,
  NotFoundException,
  BadRequestException,
} from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { AiService } from '../ai/ai.service';
import { AiOrchestratorService } from '../ai/ai-orchestrator.service';

@Injectable()
export class ArtefactsService {
  constructor(
    private readonly supabaseService: SupabaseService,
    private readonly aiService: AiService,
    private readonly aiOrchestratorService: AiOrchestratorService,
  ) {}

  async findAll(projectId: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('artefacts')
      .select('*')
      .eq('project_id', projectId);

    if (error) throw new InternalServerErrorException(error.message);
    return data;
  }

  async findOne(projectId: string, id: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('artefacts')
      .select('*')
      .eq('project_id', projectId)
      .eq('id', id)
      .single();

    if (error || !data) throw new NotFoundException('Artefact not found');
    return data;
  }

  async generate(projectId: string, payload: any, userId: string) {
    // 1. Human-in-the-loop Check
    if (payload.agentType === 'code-generator') {
      const { data: srsArtefacts } = await this.supabaseService
        .getClient()
        .from('artefacts')
        .select('id, status')
        .eq('project_id', projectId)
        .eq('type', 'srs')
        .in('status', ['approved', 'final']);

      if (!srsArtefacts || srsArtefacts.length === 0) {
        throw new BadRequestException(
          'Code generation requires an approved SRS (Software Requirements Specification) artefact first. Please generate and approve an SRS artefact.',
        );
      }
    }

    // Fetch last 4 artefacts for chat history
    let chatHistory: any[] = [];
    try {
      const { data: recentArtefacts } = await this.supabaseService
        .getClient()
        .from('artefacts')
        .select('content, metadata, created_at')
        .eq('project_id', projectId)
        .order('created_at', { ascending: false })
        .limit(4);

      if (recentArtefacts && recentArtefacts.length > 0) {
        // Supabase returns newest first, we want oldest first for history
        recentArtefacts.reverse().forEach((art: any) => {
          if (art.metadata && art.metadata.prompt) {
            chatHistory.push({
              prompt: art.metadata.prompt,
              content: art.content,
            });
          }
        });
      }
    } catch (e) {
      console.error('Failed to fetch chat history', e);
    }

    // 2. Call Gemini to generate content with RAG Memory & Chat History
    const aiResult = await this.aiOrchestratorService.generateArtefact(
      payload.agentType,
      payload.prompt,
      projectId,
      chatHistory,
      userId
    );

    // 3. Save to Supabase
    const { data, error } = await this.supabaseService
      .getClient()
      .from('artefacts')
      .insert({
        project_id: projectId,
        type: payload.type || 'code',
        name: `Generated by ${payload.agentType}`,
        content: aiResult.text,
        format: 'markdown',
        status: 'draft',
        generated_by: payload.agentType,
        metadata: { tokens: aiResult.usage, prompt: payload.prompt, ragCitations: aiResult.ragCitations },
      })
      .select()
      .single();

    if (error) {
      console.error('ArtefactsService.generate DB Error:', error);
      throw new InternalServerErrorException(error.message);
    }

    // 4. Autonomous QA Trigger (Fire and Forget)
    if (payload.agentType === 'code-generator' || payload.type === 'code') {
      // Intentionally not awaiting so it runs in the background
      this.triggerAutonomousQA(projectId, data.content, userId).catch(console.error);
    }

    return data;
  }

  private async triggerAutonomousQA(projectId: string, sourceCode: string, userId: string) {
    try {
      console.log(`[Autonomous QA] Triggering tests for project ${projectId}...`);
      const prompt = `[AUTO-QA] Generate Cypress E2E tests for the following code:\n\n${sourceCode}`;
      
      const aiResult = await this.aiOrchestratorService.generateArtefact(
        'qa-tester',
        prompt,
        projectId,
        [],
        userId
      );

      const { data, error } = await this.supabaseService
        .getClient()
        .from('artefacts')
        .insert({
          project_id: projectId,
          type: 'test',
          name: 'Auto-Generated Tests (Cypress)',
          content: aiResult.text,
          format: 'markdown',
          status: 'draft',
          generated_by: 'qa-tester',
          metadata: { tokens: aiResult.usage, prompt: prompt, is_auto_generated: true },
        })
        .select()
        .single();

      if (error) {
        console.error('[Autonomous QA] DB Error:', error);
      } else {
        console.log(`[Autonomous QA] Successfully generated test artefact: ${data.id}`);
      }
    } catch (e) {
      console.error('[Autonomous QA] Failed to generate tests:', e);
    }
  }

  async update(projectId: string, id: string, payload: any, userId?: string) {
    const supabase = this.supabaseService.getClient();
    let updatePayload = { ...payload };

    // RAG Memory: Save embedding when an artefact is approved
    if (payload.status === 'approved' || payload.status === 'final') {
      try {
        // Fetch content to embed if not provided in payload
        const contentToEmbed = payload.content || (await this.findOne(projectId, id)).content;
        if (contentToEmbed) {
          const embedding = await this.aiService.generateEmbedding(contentToEmbed, userId);
          if (embedding && embedding.length > 0) {
            // Stringify as array string for Supabase vector column
            updatePayload.embedding = `[${embedding.join(',')}]`;
            console.log(`[RAG] Saved embedding memory for artefact ${id}`);
          }
        }
      } catch (e) {
        console.error('[RAG] Failed to save embedding memory', e);
      }
    }

    const { data, error } = await supabase
      .from('artefacts')
      .update(updatePayload)
      .eq('project_id', projectId)
      .eq('id', id)
      .select()
      .single();

    if (error) throw new InternalServerErrorException(error.message);
    return data;
  }

  async refactorArtefact(projectId: string, id: string, prompt: string, userId: string) {
    // 1. Fetch existing artefact
    const artefact = await this.findOne(projectId, id);

    // 2. Build refactoring prompt
    const fullPrompt = `[EXISTING CODE/CONTENT]:\n${artefact.content}\n\n[USER INSTRUCTION - REFACTOR/MODIFY THIS ARTEFACT]:\n${prompt}`;

    // 3. Call AI with the original agent type and project context
    const agentType = artefact.generated_by || 'code-generator';
    const aiResult = await this.aiOrchestratorService.generateArtefact(
      agentType,
      fullPrompt,
      projectId,
      [],
      userId
    );

    // 4. Return as a proposal (do not overwrite DB yet)
    return {
      originalId: id,
      proposedContent: aiResult.text,
      usage: aiResult.usage,
    };
  }

  async magicBuild(projectId: string, prompt: string, userId: string) {
    // Fire and forget so we don't block the request
    this.runMagicBuildPipeline(projectId, prompt, userId).catch(console.error);
    return { status: 'started', message: 'Magic Build pipeline started in background' };
  }

  private async runMagicBuildPipeline(projectId: string, userPrompt: string, userId: string) {
    try {
      console.log(`[Magic Build] Started for project ${projectId}`);
      
      // Step 1: Ideator (SRS)
      console.log(`[Magic Build] Step 1: Ideator`);
      const srsPayload = { type: 'srs', agentType: 'ideator', prompt: userPrompt };
      const srsArtefact = await this.generate(projectId, srsPayload, userId);
      await this.update(projectId, srsArtefact.id, { status: 'approved' }, userId); // Auto-approve for the pipeline

      // Step 2: Diagrammer
      console.log(`[Magic Build] Step 2: Diagrammer`);
      const diagramPrompt = `Based on the SRS we just created for "${userPrompt}", create a system architecture diagram.`;
      const diagramPayload = { type: 'diagram', agentType: 'diagrammer', prompt: diagramPrompt };
      const diagramArtefact = await this.generate(projectId, diagramPayload, userId);
      await this.update(projectId, diagramArtefact.id, { status: 'approved' }, userId);

      // Step 3: Coder
      console.log(`[Magic Build] Step 3: Coder`);
      const codePrompt = `Based on the SRS and Architecture diagram we just created for "${userPrompt}", write the full source code for the main application entry point (e.g., App.jsx or similar) that satisfies the requirements. Use Tailwind CSS if styling is needed.`;
      const codePayload = { type: 'code', agentType: 'code-generator', prompt: codePrompt };
      await this.generate(projectId, codePayload, userId);

      console.log(`[Magic Build] Finished successfully for project ${projectId}`);
    } catch (e) {
      console.error(`[Magic Build] Failed for project ${projectId}`, e);
    }
  }
}
