import {
  Injectable,
  InternalServerErrorException,
  NotFoundException,
} from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { Octokit } from '@octokit/rest';

@Injectable()
export class ProjectsService {
  constructor(private readonly supabaseService: SupabaseService) {}

  async findAll(userId: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .select('*')
      .eq('owner_id', userId); // For now, only fetch owned projects (RLS will also filter)

    if (error) {
      console.error('ProjectsService.findAll Error:', error);
      throw new InternalServerErrorException(error.message);
    }
    return data;
  }

  async create(userId: string, createProjectDto: any) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .insert({
        ...createProjectDto,
        owner_id: userId,
      })
      .select()
      .single();

    if (error) {
      console.error('ProjectsService.create Error:', error);
      throw new InternalServerErrorException(error.message);
    }
    return data;
  }

  async findOne(userId: string, id: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .select('*')
      .eq('id', id)
      .single();

    if (error || !data) {
      throw new NotFoundException('Project not found');
    }
    return data;
  }

  async deployToGithub(userId: string, projectId: string) {
    // 1. Get user's github token from preferences
    const { data: profile } = await this.supabaseService
      .getClient()
      .from('profiles')
      .select('preferences')
      .eq('id', userId)
      .single();

    const githubToken = profile?.preferences?.githubToken;
    if (!githubToken) {
      throw new Error(
        'GitHub Personal Access Token not found. Please add it in Settings > API Keys.',
      );
    }

    // 2. Fetch project details and approved/final artefacts
    const [project, { data: artefacts }] = await Promise.all([
      this.findOne(userId, projectId),
      this.supabaseService
        .getClient()
        .from('artefacts')
        .select('*')
        .eq('project_id', projectId)
        .in('status', ['approved', 'final']),
    ]);

    if (!artefacts || artefacts.length === 0) {
      throw new Error('No approved artefacts found to deploy.');
    }

    // 3. Initialize Octokit
    const octokit = new Octokit({ auth: githubToken });
    const repoName = project.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

    try {
      // 4. Get authenticated user
      const { data: user } = await octokit.rest.users.getAuthenticated();
      const owner = user.login;

      // 5. Create or get repository
      try {
        await octokit.rest.repos.get({ owner, repo: repoName });
      } catch (err: any) {
        if (err.status === 404) {
          await octokit.rest.repos.createForAuthenticatedUser({
            name: repoName,
            description: project.description || 'Generated by BuildIA',
            private: true,
            auto_init: true,
          });
        } else {
          throw err;
        }
      }

      // 6. Push files (Simple loop for prototype, a real implementation would use trees/commits API for bulk push)
      for (const art of artefacts) {
        const path =
          art.type === 'code'
            ? `src/${art.name.replace(/\s+/g, '_')}.${art.format || 'txt'}`
            : `docs/${art.name.replace(/\s+/g, '_')}.${art.format || 'md'}`;

        let sha = undefined;
        try {
          const { data: fileData } = (await octokit.rest.repos.getContent({
            owner,
            repo: repoName,
            path,
          })) as any;
          sha = fileData.sha;
        } catch (e) {
          // File doesn't exist yet, safe to ignore
        }

        await octokit.rest.repos.createOrUpdateFileContents({
          owner,
          repo: repoName,
          path,
          message: `BuildIA: Add ${art.name}`,
          content: Buffer.from(art.content).toString('base64'),
          sha,
        });
      }

      // 7. Update project status
      await this.supabaseService
        .getClient()
        .from('projects')
        .update({ status: 'deployed' })
        .eq('id', projectId);

      return {
        success: true,
        repoUrl: `https://github.com/${owner}/${repoName}`,
      };
    } catch (error: any) {
      console.error('GitHub Deployment Error:', error);
      throw new InternalServerErrorException(
        error.message || 'Failed to deploy to GitHub',
      );
    }
  }
}
