import {
  Injectable,
  InternalServerErrorException,
  NotFoundException,
} from '@nestjs/common';
import { SupabaseService } from '../supabase/supabase.service';
import { Octokit } from '@octokit/rest';

@Injectable()
export class ProjectsService {
  constructor(private readonly supabaseService: SupabaseService) {}

  async findAll(userId: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .select('*')
      .eq('owner_id', userId); // For now, only fetch owned projects (RLS will also filter)

    if (error) {
      console.error('ProjectsService.findAll Error:', error);
      throw new InternalServerErrorException(error.message);
    }
    return data;
  }

  async create(userId: string, createProjectDto: any) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .insert({
        ...createProjectDto,
        owner_id: userId,
      })
      .select()
      .single();

    if (error) {
      console.error('ProjectsService.create Error:', error);
      throw new InternalServerErrorException(error.message);
    }
    return data;
  }

  async findOne(userId: string, id: string) {
    const { data, error } = await this.supabaseService
      .getClient()
      .from('projects')
      .select('*')
      .eq('id', id)
      .eq('owner_id', userId) // Defense-in-depth: enforce ownership server-side, not just via RLS
      .single();

    if (error || !data) {
      throw new NotFoundException('Project not found');
    }
    return data;
  }

  async deployToGithub(userId: string, projectId: string) {
    // 1. Get user's github token from preferences
    const { data: profile } = await this.supabaseService
      .getClient()
      .from('profiles')
      .select('preferences')
      .eq('id', userId)
      .single();

    const githubToken = profile?.preferences?.githubToken;
    if (!githubToken) {
      throw new Error(
        'GitHub Personal Access Token not found. Please add it in Settings > API Keys.',
      );
    }

    // 2. Fetch project details and approved/final artefacts
    const [project, { data: artefacts }] = await Promise.all([
      this.findOne(userId, projectId),
      this.supabaseService
        .getClient()
        .from('artefacts')
        .select('*')
        .eq('project_id', projectId)
        .in('status', ['approved', 'final']),
    ]);

    if (!artefacts || artefacts.length === 0) {
      throw new Error('No approved artefacts found to deploy.');
    }

    // 3. Initialize Octokit
    const octokit = new Octokit({ auth: githubToken });
    const repoName = project.name.toLowerCase().replace(/[^a-z0-9]/g, '-');

    try {
      // 4. Get authenticated user
      const { data: user } = await octokit.rest.users.getAuthenticated();
      const owner = user.login;

      // 5. Create or get repository
      let isNewRepo = false;
      try {
        await octokit.rest.repos.get({ owner, repo: repoName });
      } catch (err: any) {
        if (err.status === 404) {
          await octokit.rest.repos.createForAuthenticatedUser({
            name: repoName,
            description: project.description || 'Generated by BuildIA',
            private: true,
            auto_init: true,
          });
          isNewRepo = true;
        } else {
          throw err;
        }
      }

      // 6. Atomic bulk push using GitHub Trees API
      // Build blobs in parallel (no rate-limit risk — blobs are content-only, no branch ops)
      const blobPromises = artefacts.map(async (art) => {
        const filePath =
          art.type === 'code'
            ? `src/${art.name.replace(/\s+/g, '_')}.${art.format || 'txt'}`
            : `docs/${art.name.replace(/\s+/g, '_')}.${art.format || 'md'}`;

        const { data: blob } = await octokit.rest.git.createBlob({
          owner,
          repo: repoName,
          content: art.content,
          encoding: 'utf-8',
        });

        return {
          path: filePath,
          mode: '100644' as const,
          type: 'blob' as const,
          sha: blob.sha,
        };
      });

      const treeItems = await Promise.all(blobPromises);

      // Get base tree SHA from the default branch
      const { data: refData } = await octokit.rest.git.getRef({
        owner,
        repo: repoName,
        ref: 'heads/main',
      });
      const baseSha = refData.object.sha;

      // Get the current commit to get its tree SHA
      const { data: baseCommit } = await octokit.rest.git.getCommit({
        owner,
        repo: repoName,
        commit_sha: baseSha,
      });

      // Create new tree atomically
      const { data: newTree } = await octokit.rest.git.createTree({
        owner,
        repo: repoName,
        base_tree: baseCommit.tree.sha,
        tree: treeItems,
      });

      // Create the commit
      const { data: newCommit } = await octokit.rest.git.createCommit({
        owner,
        repo: repoName,
        message: `BuildIA: Deploy ${artefacts.length} artefact(s) from project "${project.name}"`,
        tree: newTree.sha,
        parents: [baseSha],
      });

      // Update the branch ref to point to the new commit (atomic!)
      await octokit.rest.git.updateRef({
        owner,
        repo: repoName,
        ref: 'heads/main',
        sha: newCommit.sha,
      });

      // 7. Update project status
      await this.supabaseService
        .getClient()
        .from('projects')
        .update({ status: 'deployed' })
        .eq('id', projectId);

      return {
        success: true,
        repoUrl: `https://github.com/${owner}/${repoName}`,
        commitSha: newCommit.sha,
      };
    } catch (error: any) {
      console.error('GitHub Deployment Error:', error);
      throw new InternalServerErrorException(
        error.message || 'Failed to deploy to GitHub',
      );
    }
  }
}
